# Site settings
title: Frankish History Podcast
email: podcast+claytonkucera@gmail.com
description: "A narrative history podcast detailing the history of everyone's favorite Germanic people, the Franks, with a specific focus on the Carolingian Empire."
baseurl: ""
url: "https://frankish-history-podcast.com"
paginate: 10
paginate_path: "posts/:num"

# Build settings
markdown: kramdown
permalink: pretty

# Podcast settings
lang: en
author: Clayton Kucera

# Jekyll plugins
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-paginate
  
jekyll-mentions: https://twitter.com
